In [6]:
train_data_path = '../../../data/predictor/cof/rth_1.0/features/features_rth_1.0_ecfp_2_1024_False_descriptor__custom_pattern_False.csv'
train_data_feature_types = '../../../data/predictor/cof/rth_1.0/feature_types/feature_types_rth_1.0_ecfp_2_1024_False_descriptor__custom_pattern_False.yaml'

In [7]:
import pandas as pd
import yaml

df_train = pd.read_csv(train_data_path)
with open(train_data_feature_types, 'r') as f:
    train_data_feature_types = yaml.safe_load(f)

In [11]:
import os
import copy
from modules.predictor.training_and_evaluation.sklearn_pipeline import SklearnTrainingPipeline
from modules.predictor.data.utils import custom_data_kfold

X = df_train.drop(columns=["capacity_max", 'smiles'])
y = df_train[["capacity_max"]]
folds = custom_data_kfold(X, y, num_splits=10, num_bins=10, random_state=42)
model = 'xgboost'
d_name = 'cof_rth_1.0_ecfp_2_1024_False_descriptor_custom_pattern_False'
results_dir = 'results'

save_dir = os.path.join(results_dir, model, d_name)
print(d_name, model, save_dir)
os.makedirs(save_dir, exist_ok=True)

cof_rth_1.0_ecfp_2_1024_False_descriptor_custom_pattern_False xgboost results/xgboost/cof_rth_1.0_ecfp_2_1024_False_descriptor_custom_pattern_False

In [12]:
pipeline = SklearnTrainingPipeline(
    X=copy.deepcopy(X),
    y=copy.deepcopy(y),
    feature_types=train_data_feature_types,
    folds=copy.deepcopy(folds),
    metrics=['rmse', 'mae', 'r2', 'pairwise_accuracy_score'],
    save_dir=save_dir,
    data_name=d_name,
    hyperparam_opt=True,
    num_bins=10,
    verbose=True,
)

In [13]:
model = pipeline.train_and_save_model(model)

Training final model XGBoost Regressor on the entire dataset
Best score: 172.21936396734284
 Best params: {'n_estimators': 45, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 3, 'gamma': 0.1, 'colsample_bytree': 0.3}
Model saved to results/xgboost/cof_rth_1.0_ecfp_2_1024_False_descriptor_custom_pattern_False/models/model_final.joblib

In [14]:
test_data_path = '../../../data/generated/ceteefy.csv'
cof_data_path = '../../../data/predictor/cof/data_substrate_cofs.csv'

test_data = pd.read_csv(test_data_path)
cof_data = pd.read_csv(cof_data_path)

test_data.head()

,canon_smiles,smarts_filter,conjugation_filter,flatness,normalized_csm,similarity,steric_hindrance,selfies
0,N#Cc1ccc(C#N)cc1,1,1,0.005030,0.000860,0.390080,1,[N][#C][C][=C][C][=C][Branch1][Ring1][C][#N][C...
1,N#Cc1ccc(-n2c(-c3c(F)c(F)cc(F)c3F)cc3c2cc(-c2c...,1,1,1.300015,0.067548,0.385453,1,[N][#C][C][=C][C][=C][Branch2][=Branch1][Ring1...
2,N#Cc1ccc(-n2c(=O)c3cc4c(=O)n(-c5ccc(C#N)cc5)c(...,1,1,0.706897,0.000203,0.374693,1,[N][#C][C][=C][C][=C][Branch2][Ring2][=N][N][C...
3,N#Cc1ccc(-n2[nH]c(=O)c3cc4c(=O)[nH]n(-c5ccc(C#...,1,1,0.697726,0.000662,0.319701,1,[N][#C][C][=C][C][=C][Branch2][Ring2][#C][N][N...
4,N#Cc1ccc(-n2c(-c3cc4ccccc4s3)cc3c2cc(-c2cc4ccc...,1,1,1.030009,0.000083,0.344513,1,[N][#C][C][=C][C][=C][Branch2][Branch1][#Branc...

In [15]:
test_data = test_data[['canon_smiles']]
test_data = test_data.rename(columns={'canon_smiles': 'smiles'})
test_data['capacity_max'] = 0
test_data.head()

                                              smiles  capacity_max
0                                   N#Cc1ccc(C#N)cc1             0
1  N#Cc1ccc(-n2c(-c3c(F)c(F)cc(F)c3F)cc3c2cc(-c2c...             0
2  N#Cc1ccc(-n2c(=O)c3cc4c(=O)n(-c5ccc(C#N)cc5)c(...             0
3  N#Cc1ccc(-n2[nH]c(=O)c3cc4c(=O)[nH]n(-c5ccc(C#...             0
4  N#Cc1ccc(-n2c(-c3cc4ccccc4s3)cc3c2cc(-c2cc4ccc...             0

In [16]:
concat_data = pd.concat([cof_data, test_data], axis=0, ignore_index=True)
concat_data

                                                 smiles  capacity_max
0                                      N#Cc1ccc(C#N)cc1         628.0
1     CC(C)c1ccc(-n2c(-c3ccc(C#N)cc3)cc3c2cc(-c2ccc(...         255.0
2     Cc1ccc2nc(-n3c(-c4ccc(C#N)cc4)cc4c3cc(-c3ccc(C...         269.0
3     Clc1nc(Cl)nc(-c2ccc(-c3cc(-c4ccc(-c5nc(Cl)nc(C...         228.0
4     O=C1c2ccc(Nc3nc(Cl)nc(Cl)n3)cc2C(=O)c2ccc(Nc3n...         468.0
...                                                 ...           ...
2748  N#Cc1ccc(-n2c(=O)c3cc4c(=O)n(-c5ccc(C#N)c(-c6c...           0.0
2749                  N#CC(C#N)=c1cc2c(=C(C#N)C#N)cc1-2           0.0
2750                  N#CC(C#N)=c1ccc(=C(C#N)C#N)c2c1C2           0.0
2751                 CC1c2c1c(=C(C#N)C#N)ccc2=C(C#N)C#N           0.0
2752  CC=CC=CCCCCC=COC#CC(C)=CC=CCCC=CC=Cc1cc(-c2ccc...           0.0

[2753 rows x 2 columns]

In [21]:
from modules.predictor.features.custom_descriptor import *
from modules.predictor.features.custom_patterns import *
from modules.predictor.features.feature_factory import *
from modules.predictor.features.fingerprints import *

data_types = [ "ecfp", "descriptor", "custom_pattern" ]
data_params = {
        "ecfp": {
            "radius": 2,
            "size": 1024,
            "count": False
        },
        "descriptor": {
        },
        "custom_pattern": {
            "count": False
        }
    }
kwargs = {'kwargs': data_params}
concat_data_features = generate_features(concat_data, {}, 'smiles', 'capacity_max', data_types, 1.0, **kwargs)
concat_data_features

2753it [00:02, 1198.77it/s]

(      ecfp_1  ecfp_2  ecfp_3  ecfp_4  ecfp_5  ecfp_6  ecfp_7  ecfp_8  ecfp_9  \
 0        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
 1        1.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0
 2        0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0
 3        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
 4        1.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
 ...      ...     ...     ...     ...     ...     ...     ...     ...     ...
 2748     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
 2749     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
 2750     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
 2751     0.0     0.0     0.0     0.0     0.0     0.0     1.0     0.0     0.0
 2752     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0

       ecfp_10  ...        c%  custom_pattern_0  custom_pattern_1  \
 0         0.0  ...  0.800000               0.0               0.0
 1         0.0  ...  0.904762               0.0               0.0
 2         0.0  ...  0.818182               0.0               0.0
 3         0.0  ...  0.687500               0.0               1.0
 4         0.0  ...  0.588235               0.0               0.0
 ...       ...  ...       ...               ...               ...
 2748      0.0  ...  0.769231               0.0               1.0
 2749      0.0  ...  0.750000               0.0               0.0
 2750      0.0  ...  0.764706               0.0               0.0
 2751      0.0  ...  0.777778               0.0               0.0
 2752      0.0  ...  0.926829               0.0               1.0

       custom_pattern_2  custom_pattern_3  custom_pattern_4  custom_pattern_5  \
 0                  0.0               0.0               1.0               0.0
 1                  0.0               0.0               1.0               0.0
 2                  0.0               0.0               1.0               0.0
 3                  0.0               1.0               0.0               0.0
 4                  0.0               1.0               0.0               0.0
 ...                ...               ...               ...               ...
 2748               0.0               0.0               1.0               0.0
 2749               0.0               0.0               0.0               0.0
 2750               0.0               0.0               0.0               0.0
 2751               0.0               0.0               0.0               0.0
 2752               0.0               0.0               1.0               1.0

       custom_pattern_6  capacity_max  \
 0                  0.0         628.0
 1                  0.0         255.0
 2                  0.0         269.0
 3                  0.0         228.0
 4                  0.0         468.0
 ...                ...           ...
 2748               0.0           0.0
 2749               0.0           0.0
 2750               0.0           0.0
 2751               0.0           0.0
 2752               0.0           0.0

                                                  smiles
 0                                      N#Cc1ccc(C#N)cc1
 1     CC(C)c1ccc(-n2c(-c3ccc(C#N)cc3)cc3c2cc(-c2ccc(...
 2     Cc1ccc2nc(-n3c(-c4ccc(C#N)cc4)cc4c3cc(-c3ccc(C...
 3     Clc1nc(Cl)nc(-c2ccc(-c3cc(-c4ccc(-c5nc(Cl)nc(C...
 4     O=C1c2ccc(Nc3nc(Cl)nc(Cl)n3)cc2C(=O)c2ccc(Nc3n...
 ...                                                 ...
 2748  N#Cc1ccc(-n2c(=O)c3cc4c(=O)n(-c5ccc(C#N)c(-c6c...
 2749                  N#CC(C#N)=c1cc2c(=C(C#N)C#N)cc1-2
 2750                  N#CC(C#N)=c1ccc(=C(C#N)C#N)c2c1C2
 2751                 CC1c2c1c(=C(C#N)C#N)ccc2=C(C#N)C#N
 2752  CC=CC=CCCCCC=COC#CC(C)=CC=CCCC=CC=Cc1cc(-c2ccc...

 [2753 rows x 1038 columns],
 {'categorical': [],
  'binary': ['ecfp_0',
   'ecfp_1',
   'ecfp_2',
   'ecfp_3',
   'ecfp_4',
   'ecfp_5',
   'ecfp_6',
   'ecfp_7',
   'ecfp_8',
   'ecfp_9',
   'ecfp_10',
   'ecfp_11',
   'ecfp_12',
   'ecfp_13',
   'ecfp_14',
   'ecfp_15',
   'ecfp_16',
   'ecfp_17',
   'ecfp_18',
   'ecfp_19',
   'ecfp_20',
   'ecfp_21',
   'ecfp_22',
   'ecfp_23',
   'ecfp_24',
   'ecfp_25',
   'ecfp_26',
   'ecfp_27',
   'ecfp_28',
   'ecfp_29',
   'ecfp_30',
   'ecfp_31',
   'ecfp_32',
   'ecfp_33',
   'ecfp_34',
   'ecfp_35',
   'ecfp_36',
   'ecfp_37',
   'ecfp_38',
   'ecfp_39',
   'ecfp_40',
   'ecfp_41',
   'ecfp_42',
   'ecfp_43',
   'ecfp_44',
   'ecfp_45',
   'ecfp_46',
   'ecfp_47',
   'ecfp_48',
   'ecfp_49',
   'ecfp_50',
   'ecfp_51',
   'ecfp_52',
   'ecfp_53',
   'ecfp_54',
   'ecfp_55',
   'ecfp_56',
   'ecfp_57',
   'ecfp_58',
   'ecfp_59',
   'ecfp_60',
   'ecfp_61',
   'ecfp_62',
   'ecfp_63',
   'ecfp_64',
   'ecfp_65',
   'ecfp_66',
   'ecfp_67',
   'ecfp_68',
   'ecfp_69',
   'ecfp_70',
   'ecfp_71',
   'ecfp_72',
   'ecfp_73',
   'ecfp_74',
   'ecfp_75',
   'ecfp_76',
   'ecfp_77',
   'ecfp_78',
   'ecfp_79',
   'ecfp_80',
   'ecfp_81',
   'ecfp_82',
   'ecfp_83',
   'ecfp_84',
   'ecfp_85',
   'ecfp_86',
   'ecfp_87',
   'ecfp_88',
   'ecfp_89',
   'ecfp_90',
   'ecfp_91',
   'ecfp_92',
   'ecfp_93',
   'ecfp_94',
   'ecfp_95',
   'ecfp_96',
   'ecfp_97',
   'ecfp_98',
   'ecfp_99',
   'ecfp_100',
   'ecfp_101',
   'ecfp_102',
   'ecfp_103',
   'ecfp_104',
   'ecfp_105',
   'ecfp_106',
   'ecfp_107',
   'ecfp_108',
   'ecfp_109',
   'ecfp_110',
   'ecfp_111',
   'ecfp_112',
   'ecfp_113',
   'ecfp_114',
   'ecfp_115',
   'ecfp_116',
   'ecfp_117',
   'ecfp_118',
   'ecfp_119',
   'ecfp_120',
   'ecfp_121',
   'ecfp_122',
   'ecfp_123',
   'ecfp_124',
   'ecfp_125',
   'ecfp_126',
   'ecfp_127',
   'ecfp_128',
   'ecfp_129',
   'ecfp_130',
   'ecfp_131',
   'ecfp_132',
   'ecfp_133',
   'ecfp_134',
   'ecfp_135',
   'ecfp_136',
   'ecfp_137',
   'ecfp_138',
   'ecfp_139',
   'ecfp_140',
   'ecfp_141',
   'ecfp_142',
   'ecfp_143',
   'ecfp_144',
   'ecfp_145',
   'ecfp_146',
   'ecfp_147',
   'ecfp_148',
   'ecfp_149',
   'ecfp_150',
   'ecfp_151',
   'ecfp_152',
   'ecfp_153',
   'ecfp_154',
   'ecfp_155',
   'ecfp_156',
   'ecfp_157',
   'ecfp_158',
   'ecfp_159',
   'ecfp_160',
   'ecfp_161',
   'ecfp_162',
   'ecfp_163',
   'ecfp_164',
   'ecfp_165',
   'ecfp_166',
   'ecfp_167',
   'ecfp_168',
   'ecfp_169',
   'ecfp_170',
   'ecfp_171',
   'ecfp_172',
   'ecfp_173',
   'ecfp_174',
   'ecfp_175',
   'ecfp_176',
   'ecfp_177',
   'ecfp_178',
   'ecfp_179',
   'ecfp_180',
   'ecfp_181',
   'ecfp_182',
   'ecfp_183',
   'ecfp_184',
   'ecfp_185',
   'ecfp_186',
   'ecfp_187',
   'ecfp_188',
   'ecfp_189',
   'ecfp_190',
   'ecfp_191',
   'ecfp_192',
   'ecfp_193',
   'ecfp_194',
   'ecfp_195',
   'ecfp_196',
   'ecfp_197',
   'ecfp_198',
   'ecfp_199',
   'ecfp_200',
   'ecfp_201',
   'ecfp_202',
   'ecfp_203',
   'ecfp_204',
   'ecfp_205',
   'ecfp_206',
   'ecfp_207',
   'ecfp_208',
   'ecfp_209',
   'ecfp_210',
   'ecfp_211',
   'ecfp_212',
   'ecfp_213',
   'ecfp_214',
   'ecfp_215',
   'ecfp_216',
   'ecfp_217',
   'ecfp_218',
   'ecfp_219',
   'ecfp_220',
   'ecfp_221',
   'ecfp_222',
   'ecfp_223',
   'ecfp_224',
   'ecfp_225',
   'ecfp_226',
   'ecfp_227',
   'ecfp_228',
   'ecfp_229',
   'ecfp_230',
   'ecfp_231',
   'ecfp_232',
   'ecfp_233',
   'ecfp_234',
   'ecfp_235',
   'ecfp_236',
   'ecfp_237',
   'ecfp_238',
   'ecfp_239',
   'ecfp_240',
   'ecfp_241',
   'ecfp_242',
   'ecfp_243',
   'ecfp_244',
   'ecfp_245',
   'ecfp_246',
   'ecfp_247',
   'ecfp_248',
   'ecfp_249',
   'ecfp_250',
   'ecfp_251',
   'ecfp_252',
   'ecfp_253',
   'ecfp_254',
   'ecfp_255',
   'ecfp_256',
   'ecfp_257',
   'ecfp_258',
   'ecfp_259',
   'ecfp_260',
   'ecfp_261',
   'ecfp_262',
   'ecfp_263',
   'ecfp_264',
   'ecfp_265',
   'ecfp_266',
   'ecfp_267',
   'ecfp_268',
   'ecfp_269',
   'ecfp_270',
   'ecfp_271',
   'ecfp_272',
   'ecfp_273',
   'ecfp_274',
   'ecfp_275',
   'ecfp_276',
   'ecfp_277',
   'ecfp_278',
   'ecfp_279',
   'ecfp_280',
   'ecfp_281',
   'ecfp_282',
   'ecfp_283',
   'ecfp_284',
   'ecfp_285',
   'ecfp_286',
   'ecfp_287',
   'ecfp_288',
   'ecfp_289',
   'ecfp_290',
   'ecfp_291',
   'ecfp_292',
   'ecfp_293',
   'ecfp_294',
   'ecfp_295',
   'ecfp_296',
   'ecfp_297',
   'ecfp_298',
   'ecfp_299',
   'ecfp_300',
   'ecfp_301',
   'ecfp_302',
   'ecfp_303',
   'ecfp_304',
   'ecfp_305',
   'ecfp_306',
   'ecfp_307',
   'ecfp_308',
   'ecfp_309',
   'ecfp_310',
   'ecfp_311',
   'ecfp_312',
   'ecfp_313',
   'ecfp_314',
   'ecfp_315',
   'ecfp_316',
   'ecfp_317',
   'ecfp_318',
   'ecfp_319',
   'ecfp_320',
   'ecfp_321',
   'ecfp_322',
   'ecfp_323',
   'ecfp_324',
   'ecfp_325',
   'ecfp_326',
   'ecfp_327',
   'ecfp_328',
   'ecfp_329',
   'ecfp_330',
   'ecfp_331',
   'ecfp_332',
   'ecfp_333',
   'ecfp_334',
   'ecfp_335',
   'ecfp_336',
   'ecfp_337',
   'ecfp_338',
   'ecfp_339',
   'ecfp_340',
   'ecfp_341',
   'ecfp_342',
   'ecfp_343',
   'ecfp_344',
   'ecfp_345',
   'ecfp_346',
   'ecfp_347',
   'ecfp_348',
   'ecfp_349',
   'ecfp_350',
   'ecfp_351',
   'ecfp_352',
   'ecfp_353',
   'ecfp_354',
   'ecfp_355',
   'ecfp_356',
   'ecfp_357',
   'ecfp_358',
   'ecfp_359',
   'ecfp_360',
   'ecfp_361',
   'ecfp_362',
   'ecfp_363',
   'ecfp_364',
   'ecfp_365',
   'ecfp_366',
   'ecfp_367',
   'ecfp_368',
   'ecfp_369',
   'ecfp_370',
   'ecfp_371',
   'ecfp_372',
   'ecfp_373',
   'ecfp_374',
   'ecfp_375',
   'ecfp_376',
   'ecfp_377',
   'ecfp_378',
   'ecfp_379',
   'ecfp_380',
   'ecfp_381',
   'ecfp_382',
   'ecfp_383',
   'ecfp_384',
   'ecfp_385',
   'ecfp_386',
   'ecfp_387',
   'ecfp_388',
   'ecfp_389',
   'ecfp_390',
   'ecfp_391',
   'ecfp_392',
   'ecfp_393',
   'ecfp_394',
   'ecfp_395',
   'ecfp_396',
   'ecfp_397',
   'ecfp_398',
   'ecfp_399',
   'ecfp_400',
   'ecfp_401',
   'ecfp_402',
   'ecfp_403',
   'ecfp_404',
   'ecfp_405',
   'ecfp_406',
   'ecfp_407',
   'ecfp_408',
   'ecfp_409',
   'ecfp_410',
   'ecfp_411',
   'ecfp_412',
   'ecfp_413',
   'ecfp_414',
   'ecfp_415',
   'ecfp_416',
   'ecfp_417',
   'ecfp_418',
   'ecfp_419',
   'ecfp_420',
   'ecfp_421',
   'ecfp_422',
   'ecfp_423',
   'ecfp_424',
   'ecfp_425',
   'ecfp_426',
   'ecfp_427',
   'ecfp_428',
   'ecfp_429',
   'ecfp_430',
   'ecfp_431',
   'ecfp_432',
   'ecfp_433',
   'ecfp_434',
   'ecfp_435',
   'ecfp_436',
   'ecfp_437',
   'ecfp_438',
   'ecfp_439',
   'ecfp_440',
   'ecfp_441',
   'ecfp_442',
   'ecfp_443',
   'ecfp_444',
   'ecfp_445',
   'ecfp_446',
   'ecfp_447',
   'ecfp_448',
   'ecfp_449',
   'ecfp_450',
   'ecfp_451',
   'ecfp_452',
   'ecfp_453',
   'ecfp_454',
   'ecfp_455',
   'ecfp_456',
   'ecfp_457',
   'ecfp_458',
   'ecfp_459',
   'ecfp_460',
   'ecfp_461',
   'ecfp_462',
   'ecfp_463',
   'ecfp_464',
   'ecfp_465',
   'ecfp_466',
   'ecfp_467',
   'ecfp_468',
   'ecfp_469',
   'ecfp_470',
   'ecfp_471',
   'ecfp_472',
   'ecfp_473',
   'ecfp_474',
   'ecfp_475',
   'ecfp_476',
   'ecfp_477',
   'ecfp_478',
   'ecfp_479',
   'ecfp_480',
   'ecfp_481',
   'ecfp_482',
   'ecfp_483',
   'ecfp_484',
   'ecfp_485',
   'ecfp_486',
   'ecfp_487',
   'ecfp_488',
   'ecfp_489',
   'ecfp_490',
   'ecfp_491',
   'ecfp_492',
   'ecfp_493',
   'ecfp_494',
   'ecfp_495',
   'ecfp_496',
   'ecfp_497',
   'ecfp_498',
   'ecfp_499',
   'ecfp_500',
   'ecfp_501',
   'ecfp_502',
   'ecfp_503',
   'ecfp_504',
   'ecfp_505',
   'ecfp_506',
   'ecfp_507',
   'ecfp_508',
   'ecfp_509',
   'ecfp_510',
   'ecfp_511',
   'ecfp_512',
   'ecfp_513',
   'ecfp_514',
   'ecfp_515',
   'ecfp_516',
   'ecfp_517',
   'ecfp_518',
   'ecfp_519',
   'ecfp_520',
   'ecfp_521',
   'ecfp_522',
   'ecfp_523',
   'ecfp_524',
   'ecfp_525',
   'ecfp_526',
   'ecfp_527',
   'ecfp_528',
   'ecfp_529',
   'ecfp_530',
   'ecfp_531',
   'ecfp_532',
   'ecfp_533',
   'ecfp_534',
   'ecfp_535',
   'ecfp_536',
   'ecfp_537',
   'ecfp_538',
   'ecfp_539',
   'ecfp_540',
   'ecfp_541',
   'ecfp_542',
   'ecfp_543',
   'ecfp_544',
   'ecfp_545',
   'ecfp_546',
   'ecfp_547',
   'ecfp_548',
   'ecfp_549',
   'ecfp_550',
   'ecfp_551',
   'ecfp_552',
   'ecfp_553',
   'ecfp_554',
   'ecfp_555',
   'ecfp_556',
   'ecfp_557',
   'ecfp_558',
   'ecfp_559',
   'ecfp_560',
   'ecfp_561',
   'ecfp_562',
   'ecfp_563',
   'ecfp_564',
   'ecfp_565',
   'ecfp_566',
   'ecfp_567',
   'ecfp_568',
   'ecfp_569',
   'ecfp_570',
   'ecfp_571',
   'ecfp_572',
   'ecfp_573',
   'ecfp_574',
   'ecfp_575',
   'ecfp_576',
   'ecfp_577',
   'ecfp_578',
   'ecfp_579',
   'ecfp_580',
   'ecfp_581',
   'ecfp_582',
   'ecfp_583',
   'ecfp_584',
   'ecfp_585',
   'ecfp_586',
   'ecfp_587',
   'ecfp_588',
   'ecfp_589',
   'ecfp_590',
   'ecfp_591',
   'ecfp_592',
   'ecfp_593',
   'ecfp_594',
   'ecfp_595',
   'ecfp_596',
   'ecfp_597',
   'ecfp_598',
   'ecfp_599',
   'ecfp_600',
   'ecfp_601',
   'ecfp_602',
   'ecfp_603',
   'ecfp_604',
   'ecfp_605',
   'ecfp_606',
   'ecfp_607',
   'ecfp_608',
   'ecfp_609',
   'ecfp_610',
   'ecfp_611',
   'ecfp_612',
   'ecfp_613',
   'ecfp_614',
   'ecfp_615',
   'ecfp_616',
   'ecfp_617',
   'ecfp_618',
   'ecfp_619',
   'ecfp_620',
   'ecfp_621',
   'ecfp_622',
   'ecfp_623',
   'ecfp_624',
   'ecfp_625',
   'ecfp_626',
   'ecfp_627',
   'ecfp_628',
   'ecfp_629',
   'ecfp_630',
   'ecfp_631',
   'ecfp_632',
   'ecfp_633',
   'ecfp_634',
   'ecfp_635',
   'ecfp_636',
   'ecfp_637',
   'ecfp_638',
   'ecfp_639',
   'ecfp_640',
   'ecfp_641',
   'ecfp_642',
   'ecfp_643',
   'ecfp_644',
   'ecfp_645',
   'ecfp_646',
   'ecfp_647',
   'ecfp_648',
   'ecfp_649',
   'ecfp_650',
   'ecfp_651',
   'ecfp_652',
   'ecfp_653',
   'ecfp_654',
   'ecfp_655',
   'ecfp_656',
   'ecfp_657',
   'ecfp_658',
   'ecfp_659',
   'ecfp_660',
   'ecfp_661',
   'ecfp_662',
   'ecfp_663',
   'ecfp_664',
   'ecfp_665',
   'ecfp_666',
   'ecfp_667',
   'ecfp_668',
   'ecfp_669',
   'ecfp_670',
   'ecfp_671',
   'ecfp_672',
   'ecfp_673',
   'ecfp_674',
   'ecfp_675',
   'ecfp_676',
   'ecfp_677',
   'ecfp_678',
   'ecfp_679',
   'ecfp_680',
   'ecfp_681',
   'ecfp_682',
   'ecfp_683',
   'ecfp_684',
   'ecfp_685',
   'ecfp_686',
   'ecfp_687',
   'ecfp_688',
   'ecfp_689',
   'ecfp_690',
   'ecfp_691',
   'ecfp_692',
   'ecfp_693',
   'ecfp_694',
   'ecfp_695',
   'ecfp_696',
   'ecfp_697',
   'ecfp_698',
   'ecfp_699',
   'ecfp_700',
   'ecfp_701',
   'ecfp_702',
   'ecfp_703',
   'ecfp_704',
   'ecfp_705',
   'ecfp_706',
   'ecfp_707',
   'ecfp_708',
   'ecfp_709',
   'ecfp_710',
   'ecfp_711',
   'ecfp_712',
   'ecfp_713',
   'ecfp_714',
   'ecfp_715',
   'ecfp_716',
   'ecfp_717',
   'ecfp_718',
   'ecfp_719',
   'ecfp_720',
   'ecfp_721',
   'ecfp_722',
   'ecfp_723',
   'ecfp_724',
   'ecfp_725',
   'ecfp_726',
   'ecfp_727',
   'ecfp_728',
   'ecfp_729',
   'ecfp_730',
   'ecfp_731',
   'ecfp_732',
   'ecfp_733',
   'ecfp_734',
   'ecfp_735',
   'ecfp_736',
   'ecfp_737',
   'ecfp_738',
   'ecfp_739',
   'ecfp_740',
   'ecfp_741',
   'ecfp_742',
   'ecfp_743',
   'ecfp_744',
   'ecfp_745',
   'ecfp_746',
   'ecfp_747',
   'ecfp_748',
   'ecfp_749',
   'ecfp_750',
   'ecfp_751',
   'ecfp_752',
   'ecfp_753',
   'ecfp_754',
   'ecfp_755',
   'ecfp_756',
   'ecfp_757',
   'ecfp_758',
   'ecfp_759',
   'ecfp_760',
   'ecfp_761',
   'ecfp_762',
   'ecfp_763',
   'ecfp_764',
   'ecfp_765',
   'ecfp_766',
   'ecfp_767',
   'ecfp_768',
   'ecfp_769',
   'ecfp_770',
   'ecfp_771',
   'ecfp_772',
   'ecfp_773',
   'ecfp_774',
   'ecfp_775',
   'ecfp_776',
   'ecfp_777',
   'ecfp_778',
   'ecfp_779',
   'ecfp_780',
   'ecfp_781',
   'ecfp_782',
   'ecfp_783',
   'ecfp_784',
   'ecfp_785',
   'ecfp_786',
   'ecfp_787',
   'ecfp_788',
   'ecfp_789',
   'ecfp_790',
   'ecfp_791',
   'ecfp_792',
   'ecfp_793',
   'ecfp_794',
   'ecfp_795',
   'ecfp_796',
   'ecfp_797',
   'ecfp_798',
   'ecfp_799',
   'ecfp_800',
   'ecfp_801',
   'ecfp_802',
   'ecfp_803',
   'ecfp_804',
   'ecfp_805',
   'ecfp_806',
   'ecfp_807',
   'ecfp_808',
   'ecfp_809',
   'ecfp_810',
   'ecfp_811',
   'ecfp_812',
   'ecfp_813',
   'ecfp_814',
   'ecfp_815',
   'ecfp_816',
   'ecfp_817',
   'ecfp_818',
   'ecfp_819',
   'ecfp_820',
   'ecfp_821',
   'ecfp_822',
   'ecfp_823',
   'ecfp_824',
   'ecfp_825',
   'ecfp_826',
   'ecfp_827',
   'ecfp_828',
   'ecfp_829',
   'ecfp_830',
   'ecfp_831',
   'ecfp_832',
   'ecfp_833',
   'ecfp_834',
   'ecfp_835',
   'ecfp_836',
   'ecfp_837',
   'ecfp_838',
   'ecfp_839',
   'ecfp_840',
   'ecfp_841',
   'ecfp_842',
   'ecfp_843',
   'ecfp_844',
   'ecfp_845',
   'ecfp_846',
   'ecfp_847',
   'ecfp_848',
   'ecfp_849',
   'ecfp_850',
   'ecfp_851',
   'ecfp_852',
   'ecfp_853',
   'ecfp_854',
   'ecfp_855',
   'ecfp_856',
   'ecfp_857',
   'ecfp_858',
   'ecfp_859',
   'ecfp_860',
   'ecfp_861',
   'ecfp_862',
   'ecfp_863',
   'ecfp_864',
   'ecfp_865',
   'ecfp_866',
   'ecfp_867',
   'ecfp_868',
   'ecfp_869',
   'ecfp_870',
   'ecfp_871',
   'ecfp_872',
   'ecfp_873',
   'ecfp_874',
   'ecfp_875',
   'ecfp_876',
   'ecfp_877',
   'ecfp_878',
   'ecfp_879',
   'ecfp_880',
   'ecfp_881',
   'ecfp_882',
   'ecfp_883',
   'ecfp_884',
   'ecfp_885',
   'ecfp_886',
   'ecfp_887',
   'ecfp_888',
   'ecfp_889',
   'ecfp_890',
   'ecfp_891',
   'ecfp_892',
   'ecfp_893',
   'ecfp_894',
   'ecfp_895',
   'ecfp_896',
   'ecfp_897',
   'ecfp_898',
   'ecfp_899',
   'ecfp_900',
   'ecfp_901',
   'ecfp_902',
   'ecfp_903',
   'ecfp_904',
   'ecfp_905',
   'ecfp_906',
   'ecfp_907',
   'ecfp_908',
   'ecfp_909',
   'ecfp_910',
   'ecfp_911',
   'ecfp_912',
   'ecfp_913',
   'ecfp_914',
   'ecfp_915',
   'ecfp_916',
   'ecfp_917',
   'ecfp_918',
   'ecfp_919',
   'ecfp_920',
   'ecfp_921',
   'ecfp_922',
   'ecfp_923',
   'ecfp_924',
   'ecfp_925',
   'ecfp_926',
   'ecfp_927',
   'ecfp_928',
   'ecfp_929',
   'ecfp_930',
   'ecfp_931',
   'ecfp_932',
   'ecfp_933',
   'ecfp_934',
   'ecfp_935',
   'ecfp_936',
   'ecfp_937',
   'ecfp_938',
   'ecfp_939',
   'ecfp_940',
   'ecfp_941',
   'ecfp_942',
   'ecfp_943',
   'ecfp_944',
   'ecfp_945',
   'ecfp_946',
   'ecfp_947',
   'ecfp_948',
   'ecfp_949',
   'ecfp_950',
   'ecfp_951',
   'ecfp_952',
   'ecfp_953',
   'ecfp_954',
   'ecfp_955',
   'ecfp_956',
   'ecfp_957',
   'ecfp_958',
   'ecfp_959',
   'ecfp_960',
   'ecfp_961',
   'ecfp_962',
   'ecfp_963',
   'ecfp_964',
   'ecfp_965',
   'ecfp_966',
   'ecfp_967',
   'ecfp_968',
   'ecfp_969',
   'ecfp_970',
   'ecfp_971',
   'ecfp_972',
   'ecfp_973',
   'ecfp_974',
   'ecfp_975',
   'ecfp_976',
   'ecfp_977',
   'ecfp_978',
   'ecfp_979',
   'ecfp_980',
   'ecfp_981',
   'ecfp_982',
   'ecfp_983',
   'ecfp_984',
   'ecfp_985',
   'ecfp_986',
   'ecfp_987',
   'ecfp_988',
   'ecfp_989',
   'ecfp_990',
   'ecfp_991',
   'ecfp_992',
   'ecfp_993',
   'ecfp_994',
   'ecfp_995',
   'ecfp_996',
   'ecfp_997',
   'ecfp_998',
   'ecfp_999',
   ...],
  'numerical': ['radius',
   'diameter',
   'num_heteroatoms',
   'num_rotatable_bonds',
   'num_h_acceptors',
   'num_h_donors',
   'tpsa',
   'mol_wt',
   'o%',
   'n%',
   'c%']})

In [22]:
concat_data_features, f_types = concat_data_features
columns_to_use = df_train.drop(columns=['capacity_max', 'smiles']).columns.tolist()
concat_data_features = concat_data_features[columns_to_use + ['smiles', 'capacity_max']]
concat_data_features

,ecfp_1,ecfp_4,ecfp_7,ecfp_8,ecfp_14,ecfp_15,ecfp_17,ecfp_18,ecfp_20,ecfp_21,...,c%,custom_pattern_0,custom_pattern_1,custom_pattern_2,custom_pattern_3,custom_pattern_4,custom_pattern_5,custom_pattern_6,smiles,capacity_max
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.800000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,N#Cc1ccc(C#N)cc1,628.0
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.904762,0.0,0.0,0.0,0.0,1.0,0.0,0.0,CC(C)c1ccc(-n2c(-c3ccc(C#N)cc3)cc3c2cc(-c2ccc(...,255.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.818182,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Cc1ccc2nc(-n3c(-c4ccc(C#N)cc4)cc4c3cc(-c3ccc(C...,269.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.687500,0.0,1.0,0.0,1.0,0.0,0.0,0.0,Clc1nc(Cl)nc(-c2ccc(-c3cc(-c4ccc(-c5nc(Cl)nc(C...,228.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.588235,0.0,0.0,0.0,1.0,0.0,0.0,0.0,O=C1c2ccc(Nc3nc(Cl)nc(Cl)n3)cc2C(=O)c2ccc(Nc3n...,468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2748,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.769231,0.0,1.0,0.0,0.0,1.0,0.0,0.0,N#Cc1ccc(-n2c(=O)c3cc4c(=O)n(-c5ccc(C#N)c(-c6c...,0.0
2749,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.750000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,N#CC(C#N)=c1cc2c(=C(C#N)C#N)cc1-2,0.0
2750,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.764706,0.0,0.0,0.0,0.0,0.0,0.0,0.0,N#CC(C#N)=c1ccc(=C(C#N)C#N)c2c1C2,0.0
2751,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.777778,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CC1c2c1c(=C(C#N)C#N)ccc2=C(C#N)C#N,0.0
2752,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.926829,0.0,1.0,0.0,0.0,1.0,1.0,0.0,CC=CC=CCCCCC=COC#CC(C)=CC=CCCC=CC=Cc1cc(-c2ccc...,0.0

In [24]:
test_data_features = concat_data_features.iloc[cof_data.shape[0]: , :].reset_index(drop=True)
test_data_features

,ecfp_1,ecfp_4,ecfp_7,ecfp_8,ecfp_14,ecfp_15,ecfp_17,ecfp_18,ecfp_20,ecfp_21,...,c%,custom_pattern_0,custom_pattern_1,custom_pattern_2,custom_pattern_3,custom_pattern_4,custom_pattern_5,custom_pattern_6,smiles,capacity_max
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.800000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,N#Cc1ccc(C#N)cc1,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.727273,0.0,0.0,0.0,0.0,1.0,0.0,0.0,N#Cc1ccc(-n2c(-c3c(F)c(F)cc(F)c3F)cc3c2cc(-c2c...,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.750000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,N#Cc1ccc(-n2c(=O)c3cc4c(=O)n(-c5ccc(C#N)cc5)c(...,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.705882,0.0,0.0,0.0,0.0,1.0,0.0,0.0,N#Cc1ccc(-n2[nH]c(=O)c3cc4c(=O)[nH]n(-c5ccc(C#...,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.857143,0.0,0.0,0.0,0.0,1.0,0.0,0.0,N#Cc1ccc(-n2c(-c3cc4ccccc4s3)cc3c2cc(-c2cc4ccc...,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2633,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.769231,0.0,1.0,0.0,0.0,1.0,0.0,0.0,N#Cc1ccc(-n2c(=O)c3cc4c(=O)n(-c5ccc(C#N)c(-c6c...,0.0
2634,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.750000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,N#CC(C#N)=c1cc2c(=C(C#N)C#N)cc1-2,0.0
2635,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.764706,0.0,0.0,0.0,0.0,0.0,0.0,0.0,N#CC(C#N)=c1ccc(=C(C#N)C#N)c2c1C2,0.0
2636,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.777778,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CC1c2c1c(=C(C#N)C#N)ccc2=C(C#N)C#N,0.0
2637,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.926829,0.0,1.0,0.0,0.0,1.0,1.0,0.0,CC=CC=CCCCCC=COC#CC(C)=CC=CCCC=CC=Cc1cc(-c2ccc...,0.0

In [25]:
X_test = test_data_features.drop(columns=['capacity_max', 'smiles'])
results = pipeline.predict_model(model, X_test)

results_smiles = pd.DataFrame({
    'smiles': test_data_features['smiles'],
    'predicted_capacity_max': results
})
results_smiles

,smiles,predicted_capacity_max
0,N#Cc1ccc(C#N)cc1,515.317017
1,N#Cc1ccc(-n2c(-c3c(F)c(F)cc(F)c3F)cc3c2cc(-c2c...,255.881927
2,N#Cc1ccc(-n2c(=O)c3cc4c(=O)n(-c5ccc(C#N)cc5)c(...,245.706055
3,N#Cc1ccc(-n2[nH]c(=O)c3cc4c(=O)[nH]n(-c5ccc(C#...,249.994095
4,N#Cc1ccc(-n2c(-c3cc4ccccc4s3)cc3c2cc(-c2cc4ccc...,565.125854
...,...,...
2633,N#Cc1ccc(-n2c(=O)c3cc4c(=O)n(-c5ccc(C#N)c(-c6c...,236.110291
2634,N#CC(C#N)=c1cc2c(=C(C#N)C#N)cc1-2,365.716339
2635,N#CC(C#N)=c1ccc(=C(C#N)C#N)c2c1C2,377.112915
2636,CC1c2c1c(=C(C#N)C#N)ccc2=C(C#N)C#N,370.189423
2637,CC=CC=CCCCCC=COC#CC(C)=CC=CCCC=CC=Cc1cc(-c2ccc...,204.796600

In [26]:
results_smiles.sort_values(by='predicted_capacity_max', inplace=True, ascending=False)
results_smiles

,smiles,predicted_capacity_max
4,N#Cc1ccc(-n2c(-c3cc4ccccc4s3)cc3c2cc(-c2cc4ccc...,565.125854
210,N#Cc1ccc(-n2c(-c3cc4ccccc4s3)cc3n(-c4ccc(C#N)c...,555.320435
0,N#Cc1ccc(C#N)cc1,515.317017
11,N#Cc1ccc(C#N)c2nsnc12,507.626770
2626,N#Cc1ccc(C#N)c2c1CC2,500.332611
...,...,...
2483,N#Cc1ccc(-c2ccc(-c3ccc(-c4ccc(-n5c(-c6cc(Br)c(...,119.835236
2486,N#CC=Cc1ccc(-n2c(-c3cccc(C#N)c3)cc3c2cc(-c2c(F...,119.307129
745,Cc1c(-c2ccc(C#N)cc2)sc(-c2ccc(-c3ccc(-c4nc5cc(...,119.019363
2371,N#Cc1ccc(-c2ccc(-c3ccc(-c4cccc(-n5c(-c6ccccc6)...,118.217987
2431,N#Cc1ccc(-c2ccc(-c3ccc(-c4ccc(-n5c(-c6ccc(C#N)...,117.294662

In [27]:
results_smiles.to_csv('results/ceteefy_cof_capacity_predictions.csv', index=False)

In [28]:
ctfs_original = pd.read_csv('../../../data/predictor/ctf/data_substrate_ctfs.csv')
ctfs_original

                                               smiles  capacity_max
0                                    N#Cc1ccc(C#N)cc1         628.0
1   CC(C)c1ccc(-n2c(-c3ccc(C#N)cc3)cc3c2cc(-c2ccc(...         255.0
2   Cc1ccc2nc(-n3c(-c4ccc(C#N)cc4)cc4c3cc(-c3ccc(C...         269.0
3                          N#Cc1c(F)c(F)c(C#N)c(F)c1F         379.0
4                      N#CC(C#N)=c1ccc(=C(C#N)C#N)cc1         383.0
5                                         N#C/C=C/C#N         404.0
6   N#Cc1ccc(-c2cc3c(cc(-c4ccc(C#N)cc4)n3-c3ccc(C#...         291.0
7          N#Cc1cc(C#N)c2ccc3c(C#N)cc(C#N)c4ccc1c2c43         500.0
8                        N#Cc1c2ccccc2c(C#N)c2ccccc12         589.0
9                                    N#Cc1cncc(C#N)c1          66.0
10                        N#Cc1ccc(-c2ccc(C#N)cc2)cc1         280.0
11                        N#Cc1ccc(-c2ccc(C#N)cn2)nc1         393.0
12                                   N#Cc1cccc(C#N)n1         435.0
13  N#Cc1ccc(-n2[nH]c(=O)c3cc4c(=O)[nH]n(-c5ccc(C#...         256.0
14  N#Cc1ccc(-n2c(=O)c3cc4c(=O)n(-c5ccc(C#N)cc5)c(...         231.0
15  N#Cc1ccc(-c2cc(-c3ccc(C#N)cc3)nc(-c3ccc(C#N)cc...         231.0
16   N#Cc1ccc(-c2nn(-c3ccc(C#N)cc3)c(=O)c3ccccc23)cc1         277.0
17         N#Cc1ccc(-c2nc3sc(-c4ccc(C#N)cc4)nc3s2)cc1         209.0
18                         Cc1c(C#N)sc2sc(C#N)c(C)c12         383.0
19                              N#Cc1ccc(C#N)c2nsnc12         587.0
20  N#Cc1ccc(-n2c(-c3c(F)c(F)c(F)c(F)c3F)cc3c2cc(-...         444.0
21  N#Cc1ccc(-n2c(-c3cc(F)c(F)cc3F)cc3c2cc(-c2cc(F...          84.0
22  N#Cc1ccc(-n2c(-c3c(F)c(F)cc(F)c3F)cc3c2cc(-c2c...         244.0
23  N#Cc1ccc(-n2c(-c3cccs3)cc3c2cc(-c2cccs2)n3-c2c...         703.0
24  N#Cc1ccc(-n2c(-c3ccccc3)cc3c2cc(-c2ccccc2)n3-c...         143.0
25  N#Cc1ccc(-n2c(-c3cc4ccccc4s3)cc3c2cc(-c2cc4ccc...         694.0
26  N#Cc1ccc(-c2c3nc(c(-c4ccc(C#N)cc4)c4ccc([nH]4)...         218.0
27  N#Cc1ccc(-c2nc3c4cccc5c6[nH]c(-c7ccc(C#N)cc7)n...         153.0
28  Cc1c(-c2cn(-c3ccc(C#N)cc3)nn2)c(C)c(-c2c(C)c(-...         228.0

In [29]:
def canon_smiles(smiles):
    from rdkit import Chem
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    return Chem.MolToSmiles(mol, canonical=True)
ctfs_original_smiles = ctfs_original['smiles'].apply(canon_smiles)
ctfs_original_smiles

0                                      N#Cc1ccc(C#N)cc1
1     CC(C)c1ccc(-n2c(-c3ccc(C#N)cc3)cc3c2cc(-c2ccc(...
2     Cc1ccc2nc(-n3c(-c4ccc(C#N)cc4)cc4c3cc(-c3ccc(C...
3                            N#Cc1c(F)c(F)c(C#N)c(F)c1F
4                        N#CC(C#N)=c1ccc(=C(C#N)C#N)cc1
5                                           N#C/C=C/C#N
6     N#Cc1ccc(-c2cc3c(cc(-c4ccc(C#N)cc4)n3-c3ccc(C#...
7            N#Cc1cc(C#N)c2ccc3c(C#N)cc(C#N)c4ccc1c2c43
8                          N#Cc1c2ccccc2c(C#N)c2ccccc12
9                                      N#Cc1cncc(C#N)c1
10                          N#Cc1ccc(-c2ccc(C#N)cc2)cc1
11                          N#Cc1ccc(-c2ccc(C#N)cn2)nc1
12                                     N#Cc1cccc(C#N)n1
13    N#Cc1ccc(-n2[nH]c(=O)c3cc4c(=O)[nH]n(-c5ccc(C#...
14    N#Cc1ccc(-n2c(=O)c3cc4c(=O)n(-c5ccc(C#N)cc5)c(...
15    N#Cc1ccc(-c2cc(-c3ccc(C#N)cc3)nc(-c3ccc(C#N)cc...
16     N#Cc1ccc(-c2nn(-c3ccc(C#N)cc3)c(=O)c3ccccc23)cc1
17           N#Cc1ccc(-c2nc3sc(-c4ccc(C#N)cc4)nc3s2)cc1
18                           Cc1c(C#N)sc2sc(C#N)c(C)c12
19                                N#Cc1ccc(C#N)c2nsnc12
20    N#Cc1ccc(-n2c(-c3c(F)c(F)c(F)c(F)c3F)cc3c2cc(-...
21    N#Cc1ccc(-n2c(-c3cc(F)c(F)cc3F)cc3c2cc(-c2cc(F...
22    N#Cc1ccc(-n2c(-c3c(F)c(F)cc(F)c3F)cc3c2cc(-c2c...
23    N#Cc1ccc(-n2c(-c3cccs3)cc3c2cc(-c2cccs2)n3-c2c...
24    N#Cc1ccc(-n2c(-c3ccccc3)cc3c2cc(-c2ccccc2)n3-c...
25    N#Cc1ccc(-n2c(-c3cc4ccccc4s3)cc3c2cc(-c2cc4ccc...
26    N#Cc1ccc(-c2c3nc(c(-c4ccc(C#N)cc4)c4ccc([nH]4)...
27    N#Cc1ccc(-c2nc3c4cccc5c6[nH]c(-c7ccc(C#N)cc7)n...
28    Cc1c(-c2cn(-c3ccc(C#N)cc3)nn2)c(C)c(-c2c(C)c(-...
Name: smiles, dtype: object

In [30]:
results_smiles['smiles'] = results_smiles['smiles'].apply(canon_smiles)
results_smiles

,smiles,predicted_capacity_max
4,N#Cc1ccc(-n2c(-c3cc4ccccc4s3)cc3c2cc(-c2cc4ccc...,565.125854
210,N#Cc1ccc(-n2c(-c3cc4ccccc4s3)cc3n(-c4ccc(C#N)c...,555.320435
0,N#Cc1ccc(C#N)cc1,515.317017
11,N#Cc1ccc(C#N)c2nsnc12,507.626770
2626,N#Cc1ccc(C#N)c2c1CC2,500.332611
...,...,...
2483,N#Cc1ccc(-c2ccc(-c3ccc(-c4ccc(-n5c(-c6cc(Br)c(...,119.835236
2486,N#CC=Cc1ccc(-n2c(-c3cccc(C#N)c3)cc3c2cc(-c2c(F...,119.307129
745,Cc1c(-c2ccc(C#N)cc2)sc(-c2ccc(-c3ccc(-c4nc5cc(...,119.019363
2371,N#Cc1ccc(-c2ccc(-c3ccc(-c4cccc(-n5c(-c6ccccc6)...,118.217987
2431,N#Cc1ccc(-c2ccc(-c3ccc(-c4ccc(-n5c(-c6ccc(C#N)...,117.294662

In [32]:
results_smiles_filtered = results_smiles[~results_smiles['smiles'].isin(ctfs_original_smiles)]
results_smiles_filtered

,smiles,predicted_capacity_max
210,N#Cc1ccc(-n2c(-c3cc4ccccc4s3)cc3n(-c4ccc(C#N)c...,555.320435
2626,N#Cc1ccc(C#N)c2c1CC2,500.332611
816,N#CC#Cc1ccc(C#N)cc1,491.868652
84,N#Cc1ccc(C#N)c(Br)c1Br,488.957947
2261,N#Cc1ccc(C#N)c(Cl)c1Cl,486.053406
...,...,...
2483,N#Cc1ccc(-c2ccc(-c3ccc(-c4ccc(-n5c(-c6cc(Br)c(...,119.835236
2486,N#CC=Cc1ccc(-n2c(-c3cccc(C#N)c3)cc3c2cc(-c2c(F...,119.307129
745,Cc1c(-c2ccc(C#N)cc2)sc(-c2ccc(-c3ccc(-c4nc5cc(...,119.019363
2371,N#Cc1ccc(-c2ccc(-c3ccc(-c4cccc(-n5c(-c6ccccc6)...,118.217987
2431,N#Cc1ccc(-c2ccc(-c3ccc(-c4ccc(-n5c(-c6ccc(C#N)...,117.294662

In [33]:
results_smiles_filtered.to_csv('results/ceteefy_cof_capacity_predictions_filtered.csv', index=False)

In [42]:
from rdkit.Chem import PandasTools

results_smiles_filtered = results_smiles_filtered[['smiles', 'predicted_capacity_max']]

PandasTools.AddMoleculeColumnToFrame(results_smiles_filtered, smilesCol='smiles', molCol='molecule')
results_smiles_filtered = results_smiles_filtered[['smiles', 'molecule', 'predicted_capacity_max']]

In [43]:
PandasTools.SaveXlsxFromFrame(results_smiles_filtered, 'ceteefy_capacity_predictions_filtered.xlsx', molCol='molecule')